--
-- Daten für Tabelle `oxcontents`
--

INSERT INTO `oxcontents` (`OXID`, `OXLOADID`, `OXSHOPID`, `OXSNIPPET`, `OXTYPE`, `OXACTIVE`, `OXACTIVE_1`, `OXPOSITION`, `OXTITLE`, `OXCONTENT`, `OXTITLE_1`, `OXCONTENT_1`, `OXACTIVE_2`, `OXTITLE_2`, `OXCONTENT_2`, `OXACTIVE_3`, `OXTITLE_3`, `OXCONTENT_3`, `OXCATID`, `OXFOLDER`, `OXTERMVERSION`, `OXTIMESTAMP`) VALUES
('2ed0ea12d74ab5bb3b128793bc5dbab5', 'oxtsinternationalfees', 'oxbaseshop', 1, 0, 1, 1, '', 'Trusted shops international fees text', 'Bei Lieferung ins Nicht-EU-Ausland können zusätzlich Zölle, Steuern und Gebühren anfallen', 'Trusted shops international fees text', 'Delivery to non-EU countries may cause additional custom, taxes and fees', 0, '', '', 0, '', '', '30e44ab83fdee7564.23264141', '', '', '2013-10-30 20:02:27'),
('4a63033aa27409f15484340011e74e55', 'oxcookiesexplanation', 'oxbaseshop', 1, 0, 1, 1, '', 'Cookies Explanation', 'Sie haben sich entschieden, keine Cookies von unserem Online-Shop zu akzeptieren. Die Cookies wurden gelöscht. Sie können in den Einstellungen Ihres Browsers die Verwendung von Cookies deaktivieren und den Online-Shop mit einigen funktionellen Einschränkungen nutzen. Sie können auch zurück zum Shop gehen, ohne die Einstellungen zu ändern, und den vollen Funktionsumfang des Online-Shops genießen.<br /><br />Informationen zu Cookies auf Wikipedia: <a href="http://de.wikipedia.org/wiki/HTTP-Cookie"><strong>http://de.wikipedia.org/wiki/HTTP-Cookie</strong></a>', 'Cookies Explanation', 'You have decided to not accept cookies from our online shop. The cookies have been removed. You can deactivate the usage of cookies in the settings of your browser and visit the online shop with some functional limitations. You can also return to the shop without changing the browser settings and enjoy the full functionality.<br /><br />Information about cookies at Wikipedia: <a href="http://en.wikipedia.org/wiki/HTTP_cookie"><strong>http://en.wikipedia.org/wiki/HTTP_cookie</strong></a>', 0, '', '', 0, '', '', '30e44ab83fdee7564.23264141', '', '', '2013-10-30 20:02:27'),
('5a8956e3105302bcc65c82044d863b81', 'oxfacebookenableinfotext', 'oxbaseshop', 1, 0, 1, 1, '', 'Facebook enable infotext', 'Hier können Informationen zur Übermittlung personenbezogener Daten an Facebook hinterlegt werden.<br /><br />Bei der Nutzung der Facebook Plugins wird eine Verbindung zu Facebook hergestellt, damit Sie Inhalte mit anderen Usern teilen können. Sollten Sie beim Besuch des Online-Shops die Plugins nutzen und gleichzeitig bei Facebook eingeloggt sein, werden personenbezogene Daten automatisch an Facebook übermittelt. Der Umfang der Datenerhebung sowie die weitere Verarbeitung und Nutzung der Daten kann in den <a href="http://www.facebook.com/policy.php" target="_blank">Datenschutzhinweisen von Facebook</a> nachgelesen und individuell konfiguriert werden.', 'Facebook enable infotext', 'Here you can leave information about the transmission of personal data to Facebook.<br /><br />While using Facebook plug-ins, a connection is established enabling the share of content with other users. Using plug-ins while browsing through the online shop being logged in on Facebook at the same time, your personal data is automatically transmitted to Facebook. You can find more information about collecting, using and processing of your personal data on <a href="http://www.facebook.com/policy.php" target="_blank">Facebook''s Privacy Policy</a>.', 0, '', '', 0, '', '', '30e44ab83fdee7564.23264141', '', '', '2013-10-30 20:02:27'),
('c402842cf0e2760c0875c1a74c4177f3', 'oxtsprotectiontext', 'oxbaseshop', 1, 0, 1, 1, '', 'Trusted shops protection text', '<p>Der Trusted Shops Käuferschutz sichert Ihren Online-Kauf ab. Mit der Übermittlung und <a href="http://www.trustedshops.com/shop/data_privacy.php?shop_id=[{$oView->getTSExcellenceId()}]" target="_blank">Speicherung</a>meiner E-Mail-Adresse zur Abwicklung des Käuferschutzes durch Trusted Shops bin ich einverstanden. <a href="http://www.trustedshops.com/shop/protection_conditions.php?shop_id=[{$oView->getTSExcellenceId()}]" target="_blank">Bedingungen</a> für den Käuferschutz.</p>', 'Trusted shops protection text', '<p>The Trusted Shops buyer protection secures your online purchase. I agree with the transfer and <a href="http://www.trustedshops.com/shop/data_privacy.php?shop_id=[{$oView->getTSExcellenceId()}]" target="_blank">saving</a>of my e-mail address for the buyer protection handling by Trusted Shops. <a href="http://www.trustedshops.com/shop/protection_conditions.php?shop_id=[{$oView->getTSExcellenceId()}]" target="_blank">Conditions</a> for the buyer protection.</p>', 0, '', '', 0, '', '', '30e44ab83fdee7564.23264141', '', '', '2013-10-30 20:02:27'),
('d0f7ac8b29909908dc20d854224944fe', 'oxnopaymentmethod', 'oxbaseshop', 1, 0, 1, 1, '', 'No payment method text', '<p>Derzeit ist keine Versandart für dieses Landdefiniert.</p><p>Wir werden versuchen, Liefermöglichkeiten zufinden und Sie über die Versandkosten informieren.</p>', 'No payment method text', '<p>Currently we have no shipping method set upfor this country.</p><p>We are aiming to find a possible deliverymethod and we will inform you as soon as possible via e-mail about the result,including further information about delivery costs.</p>', 0, '', '', 0, '', '', '30e44ab83fdee7564.23264141', '', '', '2013-10-30 20:02:27'),
('d74fdc1ed22a0d469bdcc5f003ca6575', 'oxregistrationdescription', 'oxbaseshop', 1, 0, 1, 1, '', 'Registration Description', '<p>Mit einem persönlichen Kundenkonto haben Sie folgende Vorteile:<br /> - Verwaltung der Lieferadressen<br /> - Prüfung des Bestellstatus<br /> - Bestellhistorie<br /> - persönlicher Merkzettel<br /> - persönliche Wunschliste<br /> - Newsletter-Verwaltung<br /> - Sonder- und Rabattaktionen</p>', 'Registration Description', '<p>A customer with an account has advantages like:<br /> - Administration of shipping addresses<br /> - Check order status<br /> - Order History<br /> - Personal Wish List<br /> - Personal Gift Registry<br /> - Newsletter subscription<br /> - Special offers and discounts</p>', 0, '', '', 0, '', '', '30e44ab83fdee7564.23264141', '', '', '2013-10-30 20:02:27'),
('f240baaafdf6930a88771197df2116c3', 'oxtscodmessage', 'oxbaseshop', 1, 0, 1, 1, '', 'Trusted shops cash on delivery message', 'Zzgl. 2,- EUR für die Geldübermittlung, die der Zusteller vor Ort erhebt', 'Trusted shops cash on delivery message', 'Plus 2,- EUR for money transfer that will be collected on site by messenger', 0, '', '', 0, '', '', '30e44ab83fdee7564.23264141', '', '', '2013-10-30 20:02:27');

